import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {tenantApi,venuesApi} from '../../api/services';
import type {Tenant} from '../../types';
import {Field} from '../../components/ui';
import {Check,ChevronLeft,ChevronRight,ExternalLink,Palette,MapPin,Clock3,PartyPopper} from 'lucide-react';

export default function OnboardingPage(){
  const nav=useNavigate(); const [step,setStep]=useState(1); const [tenant,setTenant]=useState<Partial<Tenant>>({}); const [venue,setVenue]=useState({name:'',type:'SPORTS_COURT',description:'',price:0,durationMinutes:60,active:true}); const [savedVenue,setSavedVenue]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{tenantApi.me().then(setTenant)},[]);
  const next=()=>setStep(s=>Math.min(5,s+1)); const back=()=>setStep(s=>Math.max(1,s-1));
  const saveTenant=async()=>{try{setTenant(await tenantApi.update(tenant));next()}catch(e:any){setError(e.message)}};
  const saveVenue=async()=>{try{if(!venue.name)return;await venuesApi.create(venue);setSavedVenue(true);next()}catch(e:any){setError(e.message)}};
  const finish=()=>{localStorage.removeItem('needs_onboarding');nav('/app')};
  return <div className="onboarding"><aside><div className="lp-brand light">Agenda<span>Hub</span></div><p>Vamos deixar seu sistema pronto.</p><div className="onboarding-steps">{['Seu negócio','Identidade','Primeiro espaço','Como reservar','Tudo pronto'].map((x,i)=><span className={step>=i+1?'done':''} key={x}><i>{step>i+1?<Check/>:i+1}</i>{x}</span>)}</div></aside><main><div className="onboarding-card"><div className="onboarding-progress"><span style={{width:`${step*20}%`}}/></div>{error&&<div className="alert danger">{error}</div>}
  {step===1&&<section><MapPin className="onboarding-icon"/><small>PASSO 1 DE 5</small><h1>Conte um pouco sobre seu negócio</h1><p>Essas informações aparecem para seus clientes.</p><Field label="Nome do estabelecimento"><input value={tenant.name||''} onChange={e=>setTenant({...tenant,name:e.target.value})}/></Field><Field label="Telefone / WhatsApp"><input value={tenant.phone||''} onChange={e=>setTenant({...tenant,phone:e.target.value})}/></Field><Field label="Endereço"><input value={tenant.address||''} onChange={e=>setTenant({...tenant,address:e.target.value})}/></Field><button className="btn primary full" onClick={saveTenant}>Continuar <ChevronRight/></button></section>}
  {step===2&&<section><Palette className="onboarding-icon"/><small>PASSO 2 DE 5</small><h1>Dê a sua cara ao sistema</h1><p>Você pode alterar tudo novamente depois.</p><Field label="Cor principal"><input value={tenant.primaryColor||'#2563eb'} onChange={e=>setTenant({...tenant,primaryColor:e.target.value})}/></Field><Field label="URL do logo"><input value={tenant.logoUrl||''} onChange={e=>setTenant({...tenant,logoUrl:e.target.value})}/></Field><Field label="URL da capa"><input value={tenant.coverUrl||''} onChange={e=>setTenant({...tenant,coverUrl:e.target.value})}/></Field><div className="onboarding-actions"><button className="btn ghost" onClick={back}><ChevronLeft/> Voltar</button><button className="btn primary" onClick={saveTenant}>Continuar <ChevronRight/></button></div></section>}
  {step===3&&<section><Clock3 className="onboarding-icon"/><small>PASSO 3 DE 5</small><h1>Cadastre seu primeiro espaço</h1><p>Pode ser uma quadra, salão, piscina ou qualquer ambiente alugável.</p><Field label="Nome"><input value={venue.name} onChange={e=>setVenue({...venue,name:e.target.value})} placeholder="Quadra 1"/></Field><div className="form-grid"><Field label="Preço inicial"><input type="number" min="0" value={venue.price} onChange={e=>setVenue({...venue,price:Number(e.target.value)})}/></Field><Field label="Duração (min)"><input type="number" min="1" value={venue.durationMinutes} onChange={e=>setVenue({...venue,durationMinutes:Number(e.target.value)})}/></Field></div><div className="onboarding-actions"><button className="btn ghost" onClick={back}><ChevronLeft/> Voltar</button><button className="btn primary" disabled={!venue.name} onClick={saveVenue}>Criar espaço <ChevronRight/></button></div></section>}
  {step===4&&<section><Clock3 className="onboarding-icon"/><small>PASSO 4 DE 5</small><h1>Agora configure os horários</h1><p>{savedVenue?'Seu espaço foi criado.':'Você pode criar o primeiro espaço depois.'} No painel, cada espaço possui disponibilidade semanal, bloqueios, preços, pacotes e adicionais.</p><div className="onboarding-feature-list"><span><Check/> Horários recorrentes por dia da semana</span><span><Check/> Bloqueios para manutenção ou eventos</span><span><Check/> Preço e duração por espaço</span><span><Check/> Estrutura preparada para pacotes e adicionais</span></div><div className="onboarding-actions"><button className="btn ghost" onClick={back}><ChevronLeft/> Voltar</button><button className="btn primary" onClick={next}>Continuar <ChevronRight/></button></div></section>}
  {step===5&&<section className="onboarding-done"><PartyPopper className="onboarding-icon"/><small>PASSO 5 DE 5</small><h1>Seu sistema está pronto para configurar</h1><p>Sua página pública já tem um endereço próprio dentro do AgendaHub.</p><div className="public-url"><span>{window.location.origin}/{tenant.slug}</span><a href={`/${tenant.slug}`} target="_blank" rel="noreferrer"><ExternalLink/></a></div><button className="btn primary full" onClick={finish}>Ir para o dashboard</button><button className="btn soft full" onClick={()=>window.open(`/${tenant.slug}`,'_blank')}>Abrir minha página pública</button></section>}
  </div></main></div>}
