import {createContext,useContext,useEffect,useMemo,useState,ReactNode} from 'react';
import {usersApi} from '../api/services';
export type Language='pt-BR'|'en-US'|'es-ES';
const dict:Record<Language,Record<string,string>>={
 'pt-BR':{'nav.overview':'Visão geral','nav.bookings':'Reservas','nav.agenda':'Agenda','nav.venues':'Espaços','nav.customers':'Clientes','nav.team':'Equipe','nav.page':'Minha página','nav.settings':'Configurações','nav.subscription':'Plano','settings.title':'Configurações','settings.subtitle':'Gerencie sua conta, segurança e preferências.','account':'Minha conta','security':'Segurança','preferences':'Preferências','notifications':'Notificações','language':'Idioma','save':'Salvar alterações','currentPlan':'Plano atual','plans':'Conheça os planos','upgrade':'Fazer upgrade','downgrade':'Programar downgrade','active':'Ativo','inactive':'Inativo'},
 'en-US':{'nav.overview':'Overview','nav.bookings':'Bookings','nav.agenda':'Calendar','nav.venues':'Spaces','nav.customers':'Customers','nav.team':'Team','nav.page':'My Page','nav.settings':'Settings','nav.subscription':'Plan','settings.title':'Settings','settings.subtitle':'Manage your account, security and preferences.','account':'My account','security':'Security','preferences':'Preferences','notifications':'Notifications','language':'Language','save':'Save changes','currentPlan':'Current plan','plans':'Plans','upgrade':'Upgrade','downgrade':'Schedule downgrade','active':'Active','inactive':'Inactive'},
 'es-ES':{'nav.overview':'Resumen','nav.bookings':'Reservas','nav.agenda':'Agenda','nav.venues':'Espacios','nav.customers':'Clientes','nav.team':'Equipo','nav.page':'Mi página','nav.settings':'Configuración','nav.subscription':'Plan','settings.title':'Configuración','settings.subtitle':'Administra tu cuenta, seguridad y preferencias.','account':'Mi cuenta','security':'Seguridad','preferences':'Preferencias','notifications':'Notificaciones','language':'Idioma','save':'Guardar cambios','currentPlan':'Plan actual','plans':'Planes','upgrade':'Mejorar plan','downgrade':'Programar cambio','active':'Activo','inactive':'Inactivo'}
};
const C=createContext<{language:Language;setLanguage:(l:Language)=>void;t:(k:string)=>string}>({language:'pt-BR',setLanguage:()=>{},t:k=>k});
export function I18nProvider({children}:{children:ReactNode}){const [language,setLanguageState]=useState<Language>(()=>(localStorage.getItem('language') as Language)||'pt-BR');const setLanguage=(l:Language)=>{setLanguageState(l);localStorage.setItem('language',l)};useEffect(()=>{document.documentElement.lang=language},[language]);const value=useMemo(()=>({language,setLanguage,t:(k:string)=>dict[language][k]??dict['pt-BR'][k]??k}),[language]);return <C.Provider value={value}>{children}</C.Provider>}
export const useI18n=()=>useContext(C);
