import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'react-router-dom';
import {publicApi} from '../../api/services';
import type {Addon,Tenant,Venue,VenuePackage} from '../../types';
import {Field,money} from '../../components/ui';
import {CalendarDays,Clock,MapPin,CheckCircle2,ChevronRight,Plus,Minus} from 'lucide-react';

type AddonSelection={addon:Addon;quantity:number};
export default function PublicBookingPage(){const {slug=''}=useParams();const [tenant,setTenant]=useState<Tenant>();const [venues,setVenues]=useState<Venue[]>([]);const [venueId,setVenueId]=useState<number>();const [date,setDate]=useState('');const [slots,setSlots]=useState<string[]>([]);const [slot,setSlot]=useState('');const [duration,setDuration]=useState(60);const [selectedPackage,setSelectedPackage]=useState<number>();const [packages,setPackages]=useState<VenuePackage[]>([]);const [addons,setAddons]=useState<Addon[]>([]);const [addonSelections,setAddonSelections]=useState<AddonSelection[]>([]);const [advancedAvailable,setAdvancedAvailable]=useState(true);const [form,setForm]=useState({customerName:'',customerPhone:'',customerEmail:'',notes:''});const [done,setDone]=useState(false);const [error,setError]=useState('');
useEffect(()=>{Promise.all([publicApi.tenant(slug),publicApi.venues(slug)]).then(([t,v])=>{setTenant(t);setVenues(v);if(v[0])setVenueId(v[0].id)}).catch((e:any)=>setError(e.message))},[slug]);
const venue=useMemo(()=>venues.find(v=>v.id===venueId),[venues,venueId]);
useEffect(()=>{if(!venue)return;setDuration(venue.minimumDurationMinutes||venue.slotDurationMinutes||venue.durationMinutes||60);setSelectedPackage(undefined);setAddonSelections([]);setPackages([]);setAddons([]);const advanced=Boolean(venue.pricingType);if(advanced){Promise.all([publicApi.packages(slug,venue.id).catch(()=>[]),publicApi.addons(slug,venue.id).catch(()=>[])]).then(([p,a])=>{setPackages(p);setAddons(a)})}else setAdvancedAvailable(false)},[venueId]);
useEffect(()=>{if(venueId&&date){const params:Record<string,number>={};if(venue?.pricingType==='HOURLY')params.durationMinutes=duration;if(venue?.pricingType==='PACKAGE'&&selectedPackage)params.packageId=selectedPackage;publicApi.slots(slug,venueId,date,params).then(s=>{setSlots(s);setSlot('')}).catch((e:any)=>setError(e.message))}},[slug,venueId,date,duration,selectedPackage]);
const pricingType=venue?.pricingType||'FIXED_SLOT';
const baseEstimate=useMemo(()=>{if(!venue)return 0;if(pricingType==='HOURLY')return Number(venue.basePrice??venue.price)*(duration/60);if(pricingType==='DAILY')return Number(venue.dailyPrice??venue.price);if(pricingType==='PACKAGE')return Number(packages.find(p=>p.id===selectedPackage)?.price??venue.price);return Number(venue.basePrice??venue.price)},[venue,pricingType,duration,packages,selectedPackage]);
const addonsEstimate=addonSelections.reduce((sum,s)=>sum+(Number(s.addon.price)*s.quantity),0);const totalEstimate=baseEstimate+addonsEstimate;
const toggleAddon=(addon:Addon)=>setAddonSelections(current=>current.some(x=>x.addon.id===addon.id)?current.filter(x=>x.addon.id!==addon.id):[...current,{addon,quantity:1}]);
const quantity=(id:number,delta:number)=>setAddonSelections(current=>current.map(x=>x.addon.id===id?{...x,quantity:Math.max(1,x.quantity+delta)}:x));
const submit=async(e:any)=>{e.preventDefault();if(!venueId||!slot)return;setError('');try{await publicApi.book(slug,{venueId,...form,startDateTime:slot,durationMinutes:pricingType==='HOURLY'?duration:undefined,packageId:selectedPackage,addons:addonSelections.map(x=>({addonId:x.addon.id,quantity:x.quantity}))});setDone(true)}catch(e:any){setError(e.message)}};
if(done)return <div className="public-page"><div className="success-screen"><CheckCircle2 size={56}/><h1>Reserva recebida!</h1><p>Seu horário foi registrado. O estabelecimento poderá confirmar a reserva e o pagamento.</p><button className="btn primary" onClick={()=>{setDone(false);setDate('');setSlot('');setAddonSelections([])}}>Fazer outra reserva</button></div></div>;
return <div className="public-page" style={{'--tenant':tenant?.primaryColor||'#2563eb'} as any}><section className="public-hero" style={tenant?.coverUrl?{backgroundImage:`linear-gradient(90deg,rgba(7,13,24,.9),rgba(7,13,24,.45)),url(${tenant.coverUrl})`}:undefined}><div className="public-container">{tenant?.logoUrl&&<img className="tenant-logo" src={tenant.logoUrl}/>}<h1>{tenant?.name||'Agendamento online'}</h1><p><MapPin size={17}/>{tenant?.address||'Escolha seu espaço e reserve em poucos passos.'}</p><div className="public-contact">{tenant?.phone&&<span>{tenant.phone}</span>}{tenant?.instagram&&<span>@{tenant.instagram.replace('@','')}</span>}</div></div></section><main className="public-container booking-flow">{error&&<div className="alert danger">{error}</div>}<div className="booking-steps"><span className={venueId?'done':''}>1 <b>Espaço</b></span><i/><span className={date?'done':''}>2 <b>Data</b></span><i/><span className={slot?'done':''}>3 <b>Horário</b></span><i/><span>4 <b>Dados</b></span></div>
<section><div className="section-label">1. Escolha o espaço</div><div className="public-venues">{venues.map(v=><button key={v.id} className={venueId===v.id?'public-venue selected':'public-venue'} onClick={()=>setVenueId(v.id)}><span className="venue-icon"><CalendarDays/></span><strong>{v.name}</strong><small>{v.description||v.type}</small><b>{v.pricingType==='HOURLY'?`${money(v.basePrice??v.price)}/h`:v.pricingType==='DAILY'?`${money(v.dailyPrice??v.price)}/dia`:money(v.basePrice??v.price)}</b><span>{v.pricingType==='PACKAGE'?'Escolha um pacote':v.pricingType==='HOURLY'?'Duração flexível':`${v.slotDurationMinutes??v.durationMinutes} min`}</span></button>)}</div></section>
{venue&&<section className="public-config"><div className="section-label">2. Como deseja reservar?</div>{pricingType==='HOURLY'&&<div className="duration-options">{Array.from({length:Math.max(1,Math.floor(((venue.maximumDurationMinutes||240)-(venue.minimumDurationMinutes||60))/(venue.durationStepMinutes||60))+1)},(_,i)=>(venue.minimumDurationMinutes||60)+i*(venue.durationStepMinutes||60)).map(min=><button key={min} className={duration===min?'selected':''} onClick={()=>setDuration(min)}>{min/60}h <small>{money(Number(venue.basePrice??venue.price)*(min/60))}</small></button>)}</div>}{pricingType==='PACKAGE'&&<div className="package-options">{packages.length?packages.map(p=><button key={p.id} className={selectedPackage===p.id?'selected':''} onClick={()=>setSelectedPackage(p.id)}><strong>{p.name}</strong><span>{p.durationMinutes/60}h · {money(p.price)}</span></button>):<div className="inline-note">Os pacotes serão exibidos aqui após a atualização da API.</div>}</div>}{pricingType==='DAILY'&&<div className="inline-note">Reserva por diária · {money(venue.dailyPrice??venue.price)}. A seleção de múltiplos dias será habilitada com a API de pricing.</div>}{pricingType==='FIXED_SLOT'&&<div className="inline-note">Horário de {venue.slotDurationMinutes??venue.durationMinutes} minutos · {money(venue.basePrice??venue.price)}</div>}</section>}
<section className="public-grid"><div><div className="section-label">3. Data</div><input className="date-input" type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/><div className="section-label mt">4. Horário disponível</div><div className="slots">{!date?<p className="muted">Selecione uma data.</p>:slots.length?slots.map(s=><button key={s} className={slot===s?'slot selected':'slot'} onClick={()=>setSlot(s)}><Clock size={15}/>{new Date(s).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</button>):<p className="muted">Nenhum horário disponível nesta data.</p>}</div>{addons.length>0&&<div className="public-addons"><div className="section-label mt">5. Adicionais</div>{addons.map(a=>{const selected=addonSelections.find(x=>x.addon.id===a.id);return <div className={selected?'addon-option selected':'addon-option'} key={a.id}><button onClick={()=>toggleAddon(a)}><span><strong>{a.name}</strong><small>{a.description||a.pricingType}</small></span><b>+ {money(a.price)}</b></button>{selected&&a.pricingType==='PER_UNIT'&&<div className="qty"><button onClick={()=>quantity(a.id,-1)}><Minus/></button><span>{selected.quantity}</span><button onClick={()=>quantity(a.id,1)}><Plus/></button></div>}</div>})}</div>}</div><div className="booking-box"><div className="section-label">{addons.length?'6':'5'}. Seus dados</div><form onSubmit={submit}><Field label="Nome"><input required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></Field><Field label="WhatsApp / telefone"><input required value={form.customerPhone} onChange={e=>setForm({...form,customerPhone:e.target.value})}/></Field><Field label="E-mail (opcional)"><input type="email" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/></Field><Field label="Observação (opcional)"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="booking-summary"><span><small>{venue?.name||'Espaço'}</small><strong>{pricingType==='HOURLY'?`${duration/60}h`:pricingType==='PACKAGE'?packages.find(p=>p.id===selectedPackage)?.name||'Pacote':'Reserva'}</strong></span>{addonSelections.map(x=><span key={x.addon.id}><small>{x.addon.name} {x.quantity>1?`×${x.quantity}`:''}</small><strong>{money(x.addon.price*x.quantity)}</strong></span>)}<div><b>Total estimado</b><strong>{money(totalEstimate)}</strong></div></div>{!advancedAvailable&&<small className="backend-note">Valor confirmado pela API atual no momento da reserva.</small>}<button disabled={!slot} className="btn tenant-btn full">Solicitar reserva <ChevronRight/></button></form></div></section></main><footer className="public-footer">Agendamento online · {tenant?.name}</footer></div>}
