import {useEffect,useState} from 'react';
import {bookingsApi,tenantApi,venuesApi,dashboardApi} from '../../api/services'; import type {Booking,Tenant,Venue,DashboardAnalytics} from '../../types'; import {Card,money} from '../../components/ui'; import {CalendarCheck,MapPin,Clock3,Banknote,Users,TrendingUp} from 'lucide-react'; import {planDefinition} from '../../config/plans';
function BarChart({data}:{data:{label:string;value:number}[]}){const max=Math.max(1,...data.map(x=>x.value));return <div className="bar-chart">{data.map(x=><div className="bar-col" key={x.label}><div className="bar" style={{height:`${Math.max(4,x.value/max*100)}%`}} title={`${x.label}: ${x.value}`}/><small>{x.label}</small></div>)}</div>}
export default function DashboardPage(){
 const [tenant,setTenant]=useState<Tenant>();const [venues,setVenues]=useState<Venue[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [analytics,setAnalytics]=useState<DashboardAnalytics>();const [period,setPeriod]=useState<'WEEK'|'MONTH'>('WEEK');const [locked,setLocked]=useState(false);
 useEffect(()=>{Promise.all([tenantApi.me(),venuesApi.list(),bookingsApi.list()]).then(([t,v,b])=>{setTenant(t);setVenues(v);setBookings(b)})},[]);
 useEffect(()=>{dashboardApi.analytics(period).then(x=>{setAnalytics(x);setLocked(false)}).catch(()=>setLocked(period==='MONTH'))},[period]);
 const today=new Date().toDateString();const todays=bookings.filter(b=>new Date(b.startDateTime).toDateString()===today);const revenue=bookings.filter(b=>b.paymentStatus==='PAID').reduce((a,b)=>a+Number(b.totalAmount),0);const plan=planDefinition(tenant?.plan);
 return <><div className="page-head"><div><h1>Olá{tenant?.name?`, ${tenant.name}`:''}</h1><p>Acompanhe a operação e os indicadores do seu negócio.</p></div></div><div className="stats"><Card><CalendarCheck/><span>Reservas hoje</span><strong>{todays.length}</strong></Card><Card><MapPin/><span>Espaços ativos</span><strong>{venues.filter(v=>v.active).length}</strong></Card><Card><Clock3/><span>Pendentes</span><strong>{bookings.filter(b=>b.status==='PENDING').length}</strong></Card><Card><Banknote/><span>Receita registrada</span><strong>{money(revenue)}</strong></Card></div>
 <Card className="analytics-card"><div className="card-head"><div><h2>Desempenho</h2><p>Reservas, faturamento, clientes e ocupação.</p></div><div className="billing-toggle"><button className={period==='WEEK'?'active':''} onClick={()=>setPeriod('WEEK')}>Semana</button><button className={period==='MONTH'?'active':''} onClick={()=>setPeriod('MONTH')}>Mês</button></div></div>
 {locked?<div className="upgrade-box"><TrendingUp size={25}/><h3>Analytics mensal é um recurso Plus</h3><p>Tenha comparativos, ocupação, ticket médio e relatórios para entender o crescimento.</p><a className="btn primary" href="/app/subscription">Conhecer o Plus</a></div>:analytics&&<><div className="analytics-kpis"><div><span>Reservas</span><strong>{analytics.reservations}</strong></div><div><span>Faturamento</span><strong>{money(analytics.revenue)}</strong></div><div><span>Clientes</span><strong>{analytics.customers}</strong></div><div><span>Ocupação</span><strong>{analytics.occupationRate.toFixed(1)}%</strong></div></div><div className="chart-grid"><div><h3>Reservas por dia</h3><BarChart data={analytics.points.map(x=>({label:new Date(`${x.date}T00:00:00`).toLocaleDateString('pt-BR',{weekday:'short'}),value:x.bookings}))}/></div><div><h3>Faturamento</h3><BarChart data={analytics.points.map(x=>({label:new Date(`${x.date}T00:00:00`).toLocaleDateString('pt-BR',{weekday:'short'}),value:Number(x.revenue)}))}/></div></div><p className="muted analytics-note">Plano {plan.label} · período de {new Date(`${analytics.start}T00:00:00`).toLocaleDateString('pt-BR')} a {new Date(`${analytics.end}T00:00:00`).toLocaleDateString('pt-BR')}</p></>}
 </Card>
 <Card><div className="card-head"><div><h2>Próximas reservas</h2><p>Reservas mais próximas do horário atual.</p></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Espaço</th><th>Status</th><th>Valor</th></tr></thead><tbody>{bookings.filter(b=>new Date(b.startDateTime)>new Date()&&b.status!=='CANCELLED').sort((a,b)=>+new Date(a.startDateTime)-+new Date(b.startDateTime)).slice(0,6).map(b=><tr key={b.id}><td>{new Date(b.startDateTime).toLocaleString('pt-BR')}</td><td>#{b.venueId}</td><td>{b.status}</td><td>{money(b.totalAmount)}</td></tr>)}</tbody></table></div></Card></>
}
