import {useEffect,useState} from 'react';
import {tenantApi,usersApi} from '../../api/services'; import type {Tenant,UserProfile} from '../../types';
import {Card,Field} from '../../components/ui'; import {useAuth} from '../../contexts/AuthContext'; import {useI18n,Language} from '../../contexts/I18nContext'; import {Lock,UserRound,Globe2,Bell,Save} from 'lucide-react';
export default function SettingsPage(){
 const [profile,setProfile]=useState<UserProfile>({name:'',email:'',username:'',language:'pt-BR'}); const [tenant,setTenant]=useState<Tenant>(); const [tab,setTab]=useState('account'); const [msg,setMsg]=useState(''); const [error,setError]=useState(''); const [password,setPassword]=useState({currentPassword:'',newPassword:''}); const {setTenantToken}=useAuth(); const {language,setLanguage,t}=useI18n();
 useEffect(()=>{Promise.all([usersApi.me(),tenantApi.me()]).then(([p,ten])=>{setProfile(p);setTenant(ten)})},[]);
 const saveProfile=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const r=await usersApi.updateMe({...profile,language});setProfile(r.profile);setTenantToken(r.token);setLanguage(r.profile.language as Language);setMsg('Alterações salvas.')}catch(e:any){setError(e.message)}};
 const saveTenant=async(e:React.FormEvent)=>{e.preventDefault();if(!tenant)return;try{setTenant(await tenantApi.update(tenant));setMsg('Preferências salvas.')}catch(e:any){setError(e.message)}};
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();try{await usersApi.changePassword(password);setPassword({currentPassword:'',newPassword:''});setMsg('Senha alterada com sucesso.')}catch(e:any){setError(e.message)}};
 const tabs=[['account',UserRound,t('account')],['security',Lock,t('security')],['preferences',Globe2,t('preferences')],['notifications',Bell,t('notifications')],['language',Globe2,t('language')]];
 return <><div className="page-head"><div><h1>{t('settings.title')}</h1><p>{t('settings.subtitle')}</p></div></div><div className="settings-layout"><Card className="settings-menu">{tabs.map(([id,Icon,label])=><button key={id as string} className={tab===id?'selected':''} onClick={()=>setTab(id as string)}><Icon size={17}/>{label as string}</button>)}</Card><Card><div className="settings-content">
 {tab==='account'&&<form onSubmit={saveProfile}><h2>{t('account')}</h2><div className="form-grid"><Field label="Nome"><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></Field><Field label="Nome de usuário"><input value={profile.username||''} onChange={e=>setProfile({...profile,username:e.target.value})}/></Field><Field label="E-mail"><input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></Field></div><button className="btn primary"><Save size={15}/>{t('save')}</button></form>}
 {tab==='security'&&<form onSubmit={changePassword}><h2>{t('security')}</h2><Field label="Senha atual"><input type="password" required value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})}/></Field><Field label="Nova senha"><input type="password" minLength={8} required value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})}/></Field><button className="btn primary"><Save size={15}/>{t('save')}</button></form>}
 {tab==='preferences'&&tenant&&<form onSubmit={saveTenant}><h2>{t('preferences')}</h2><div className="form-grid"><Field label="Fuso horário"><select value={tenant.timezone||'America/Sao_Paulo'} onChange={e=>setTenant({...tenant,timezone:e.target.value})}><option>America/Sao_Paulo</option><option>America/Fortaleza</option><option>America/Manaus</option><option>America/New_York</option><option>Europe/Lisbon</option></select></Field><Field label="Formato de data"><select value={tenant.dateFormat||'dd/MM/yyyy'} onChange={e=>setTenant({...tenant,dateFormat:e.target.value})}><option>dd/MM/yyyy</option><option>MM/dd/yyyy</option><option>yyyy-MM-dd</option></select></Field><Field label="Formato de hora"><select value={tenant.timeFormat||'24h'} onChange={e=>setTenant({...tenant,timeFormat:e.target.value})}><option value="24h">24 horas</option><option value="12h">12 horas</option></select></Field><Field label="Início da semana"><select value={tenant.weekStartsOn||'MONDAY'} onChange={e=>setTenant({...tenant,weekStartsOn:e.target.value})}><option value="MONDAY">Segunda-feira</option><option value="SUNDAY">Domingo</option></select></Field></div><button className="btn primary"><Save size={15}/>{t('save')}</button></form>}
 {tab==='notifications'&&tenant&&<form onSubmit={saveTenant}><h2>{t('notifications')}</h2>{[['notifyNewBooking','Nova reserva'],['notifyCancellation','Cancelamento'],['notifyBookingReminder','Lembrete de reserva'],['notifyEmail','E-mail'],['notifyWhatsapp','WhatsApp']].map(([k,label])=><label className="switch-row" key={k}><span>{label}</span><input type="checkbox" checked={Boolean((tenant as any)[k])} onChange={e=>setTenant({...tenant,[k]:e.target.checked})}/></label>)}<button className="btn primary"><Save size={15}/>{t('save')}</button></form>}
 {tab==='language'&&<div><h2>{t('language')}</h2><Field label="Idioma da interface"><select value={language} onChange={e=>{setLanguage(e.target.value as Language);setProfile({...profile,language:e.target.value})}}><option value="pt-BR">🇧🇷 Português</option><option value="en-US">🇺🇸 English</option><option value="es-ES">🇪🇸 Español</option></select></Field><p className="muted">O idioma é aplicado imediatamente. Salve a conta para sincronizá-lo com seu usuário.</p></div>}
 {msg&&<div className="alert success">{msg}</div>}{error&&<div className="alert danger">{error}</div>}
 </div></Card></div></>
}
