import {useEffect,useState} from 'react';
import {subscriptionApi,venuesApi,usersApi} from '../../api/services'; import type {Subscription,Plan} from '../../types'; import {Badge,Card,money} from '../../components/ui'; import {PLANS,planDefinition} from '../../config/plans'; import {Check,Sparkles,ArrowUp,ArrowDown} from 'lucide-react';
const rank=(p:Plan)=>p==='STARTER'?1:p==='PRO'?2:3;
export default function SubscriptionPage(){
 const [s,setS]=useState<Subscription>();const [venues,setVenues]=useState(0);const [users,setUsers]=useState<number|null>(null);const [cycle,setCycle]=useState('MONTHLY');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([subscriptionApi.me(),venuesApi.list(),usersApi.list()]).then(([sub,v,u])=>{setS(sub);setCycle(sub.billingCycle||'MONTHLY');setVenues(v.length);setUsers(u.length)}).catch(()=>{})},[]);
 const current=planDefinition(s?.plan);
 const change=async(p:Plan)=>{if(!s||p===s.plan)return;setBusy(true);setMessage('');try{const r=await subscriptionApi.change(p,cycle);if(r.url)window.location.href=r.url;else{setMessage(`A mudança para ${planDefinition(p).label} foi programada para o próximo ciclo.`);setS({...s,pendingPlan:p,pendingBillingCycle:cycle})}}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 return <><div className="page-head"><div><h1>Plano</h1><p>Compare os recursos e escolha o plano ideal para sua operação.</p></div><div className="billing-toggle"><button className={cycle==='MONTHLY'?'active':''} onClick={()=>setCycle('MONTHLY')}>Mensal</button><button className={cycle==='YEARLY'?'active':''} onClick={()=>setCycle('YEARLY')}>Anual <small>2 meses grátis</small></button></div></div>
 {s?.pendingPlan&&<div className="alert warning">Mudança para <strong>{planDefinition(s.pendingPlan as Plan).label}</strong> programada. {rank(s.pendingPlan as Plan)<rank(s.plan)?'Ela será aplicada no próximo ciclo de cobrança.':'Aguardando confirmação do pagamento.'}</div>}
 {message&&<div className="alert success">{message}</div>}
 <div className="subscription-overview"><Card><span className="muted">Plano atual</span><div className="current-plan"><h2>{current.label}</h2><Badge tone={s?.status==='ACTIVE'||s?.status==='TRIAL'?'success':'warning'}>{s?.status||'Carregando'}</Badge></div><div className="usage-list"><div><span>Espaços</span><strong>{venues}/{current.maxVenues}</strong></div><div className="usage-track"><span style={{width:`${Math.min(100,(venues/current.maxVenues)*100)}%`}}/></div>{users!==null&&<><div><span>Usuários</span><strong>{users}/{current.maxUsers}</strong></div><div className="usage-track"><span style={{width:`${Math.min(100,(users/current.maxUsers)*100)}%`}}/></div></>}</div><div className="subscription-meta"><div><small>Início</small><strong>{s?.startDate?new Date(`${s.startDate}T00:00:00`).toLocaleDateString('pt-BR'):'—'}</strong></div><div><small>Próxima cobrança</small><strong>{s?.nextBillingDate?new Date(`${s.nextBillingDate}T00:00:00`).toLocaleDateString('pt-BR'):'—'}</strong></div></div></Card></div>
 <h2 className="plans-title">Compare os planos</h2><div className="pricing-grid compact">{PLANS.map(p=>{const lower=s&&rank(p.value)<rank(s.plan);const same=s?.plan===p.value;return <Card key={p.value} className={p.value===s?.plan?'mini-plan current':'mini-plan'}><div className="plan-card-head"><span>{p.label}</span>{p.highlighted&&<Badge tone="success">Mais escolhido</Badge>}</div><strong>{money(cycle==='YEARLY'?p.annualPrice:p.price)}<small>{cycle==='YEARLY'?'/ano':'/mês'}</small></strong><p>{p.description}</p><div className="feature-checks compact-features">{p.features.map(x=><span key={x}><Check/> {x}</span>)}</div>{same?<Badge tone="success">Plano atual</Badge>:<button className="btn soft full" disabled={busy} onClick={()=>change(p.value)}>{lower?<><ArrowDown size={15}/>{'Programar downgrade'}</>:<><ArrowUp size={15}/>{'Fazer upgrade'}</>}</button>}</Card>})}</div><p className="muted plan-note">Upgrades são confirmados pelo pagamento. Downgrades ficam programados para o próximo ciclo para não bloquear recursos no meio do período.</p></>
}
