import {useEffect,useState} from 'react';
import {subscriptionApi,venuesApi} from '../../api/services';
import type {Subscription,Venue} from '../../types';
import {Card,money,Empty,Badge} from '../../components/ui';
import {Link} from 'react-router-dom';
import {Plus,Clock3,MoreHorizontal,Power,Trash2} from 'lucide-react';
import {planDefinition} from '../../config/plans';

const pricingLabel=(v:Venue)=>v.pricingType==='HOURLY'?'Por hora':v.pricingType==='DAILY'?'Diária':v.pricingType==='PACKAGE'?'Pacotes':'Horário fixo';
export default function VenuesPage(){const [items,setItems]=useState<Venue[]>([]);const [sub,setSub]=useState<Subscription>();const load=()=>Promise.all([venuesApi.list(),subscriptionApi.me()]).then(([v,s])=>{setItems(v);setSub(s)});useEffect(()=>{load()},[]);const plan=planDefinition(sub?.plan);const atLimit=items.length>=plan.maxVenues;return <><div className="page-head"><div><h1>Espaços</h1><p>Configure tudo que seus clientes podem reservar.</p></div><Link className={atLimit?'btn primary disabled-link':'btn primary'} to={atLimit?'#':'/app/venues/new'} onClick={e=>atLimit&&e.preventDefault()}><Plus size={17}/> Novo espaço</Link></div>
<Card className="plan-usage"><div><span>Uso do plano {plan.label}</span><strong>{items.length} de {plan.maxVenues} espaços utilizados</strong></div><div className="usage-track"><span style={{width:`${Math.min(100,(items.length/plan.maxVenues)*100)}%`}}/></div>{atLimit&&<div className="limit-message">Você chegou ao limite do seu plano. <Link to="/app/subscription">Ver opções de upgrade</Link></div>}</Card>
{!items.length?<Empty title="Nenhum espaço cadastrado" description="Crie sua primeira quadra, salão, piscina ou ambiente."/>:<div className="venue-grid">{items.map(v=><Card key={v.id} className="venue-new-card"><div className="venue-card-top"><Badge tone={v.active?'success':'neutral'}>{v.active?'Ativo':'Inativo'}</Badge><div className="actions"><button className="icon" onClick={async()=>{await venuesApi.setActive(v.id,!v.active);load()}} title={v.active?"Desativar":"Reativar"}><Power/></button><button className="icon danger-text" onClick={async()=>{if(confirm("Excluir este espaço?")){try{await venuesApi.remove(v.id);load()}catch(e:any){alert(e.message)}}}} title="Excluir"><Trash2/></button><MoreHorizontal size={18}/></div></div><div className="venue-visual"><MapIcon/></div><h3>{v.name}</h3><p>{v.description||v.type}</p><div className="venue-metrics"><span><small>Preço</small><b>{money(v.basePrice??v.dailyPrice??v.price)}</b></span><span><small>Modelo</small><b>{pricingLabel(v)}</b></span><span><small>Duração</small><b><Clock3 size={13}/>{v.slotDurationMinutes??v.durationMinutes} min</b></span></div><div className="venue-card-actions"><Link className="btn soft" to={`/app/venues/${v.id}`}>Gerenciar</Link><Link className="btn ghost" to={`/app/venues/${v.id}/edit`}>Editar</Link></div></Card>)}</div>}</>}
function MapIcon(){return <div className="venue-placeholder"><span>AH</span></div>}
