import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {venuesApi} from '../../api/services';
import type {PricingType,Venue} from '../../types';
import {Card,Field} from '../../components/ui';
import {ArrowLeft,CalendarDays,Clock3,PackageOpen,Timer} from 'lucide-react';
import {FEATURES} from '../../config/features';

type Form=Partial<Venue>&{pricingType:PricingType};
const blank:Form={name:'',description:'',type:'SPORTS_COURT',price:0,durationMinutes:60,active:true,pricingType:'FIXED_SLOT',basePrice:0,slotDurationMinutes:60,minimumDurationMinutes:60,maximumDurationMinutes:240,durationStepMinutes:60,dailyPrice:0,minimumDays:1,maximumDays:7,requiresApproval:true,requiresPayment:false};
export default function VenueFormPage(){
  const {id}=useParams(); const nav=useNavigate(); const [form,setForm]=useState<Form>(blank); const [error,setError]=useState(''); const editing=Boolean(id);
  useEffect(()=>{if(id)venuesApi.get(Number(id)).then(v=>setForm({...blank,...v,pricingType:v.pricingType||'FIXED_SLOT',basePrice:v.basePrice??v.price,slotDurationMinutes:v.slotDurationMinutes??v.durationMinutes}))},[id]);
  const set=(key:string,value:any)=>setForm(p=>({...p,[key]:value}));
  const save=async(e:any)=>{e.preventDefault();setError('');try{
    const legacyPayload={name:form.name,description:form.description,type:form.type,active:form.active,price:form.pricingType==='DAILY'?Number(form.dailyPrice||0):Number(form.basePrice||form.price||0),durationMinutes:Number(form.slotDurationMinutes||form.durationMinutes||60)};
    const payload=FEATURES.advancedPricingApi?{...form,...legacyPayload}:legacyPayload;
    editing?await venuesApi.update(Number(id),payload):await venuesApi.create(payload); nav('/app/venues');
  }catch(e:any){setError(e.message)}};
  const modes:[PricingType,string,string,any][]=[['FIXED_SLOT','Horário fixo','Ex.: 60 min por R$ 80',Clock3],['HOURLY','Por hora','Cliente escolhe a duração',Timer],['DAILY','Diária','Cobrança por dia',CalendarDays],['PACKAGE','Pacotes','Ex.: 2h, 4h ou 6h',PackageOpen]];
  return <><div className="page-head"><div><Link className="back-link" to="/app/venues"><ArrowLeft size={16}/> Espaços</Link><h1>{editing?'Editar espaço':'Novo espaço'}</h1><p>Configure como este ambiente será apresentado e reservado.</p></div></div><form onSubmit={save} className="venue-editor"><Card><h2>Informações</h2><div className="form-grid"><Field label="Nome"><input required value={form.name||''} onChange={e=>set('name',e.target.value)} placeholder="Quadra 1"/></Field><Field label="Tipo"><input required value={form.type||''} onChange={e=>set('type',e.target.value)} placeholder="Society, salão, piscina..."/></Field></div><Field label="Descrição"><textarea value={form.description||''} onChange={e=>set('description',e.target.value)} placeholder="Descreva o espaço para seus clientes."/></Field><label className="check"><input type="checkbox" checked={Boolean(form.active)} onChange={e=>set('active',e.target.checked)}/> Espaço ativo e visível para reservas</label></Card>
  <Card><h2>Como você cobra?</h2><p className="muted editor-intro">Escolha o modelo que melhor representa este espaço. Os modelos avançados já estão estruturados no frontend e serão persistidos após a evolução da API.</p><div className="pricing-modes">{modes.map(([value,title,desc,Icon])=><button type="button" className={form.pricingType===value?'pricing-mode active':'pricing-mode'} key={value} onClick={()=>set('pricingType',value)}><Icon/><strong>{title}</strong><small>{desc}</small></button>)}</div>
  {form.pricingType==='FIXED_SLOT'&&<div className="form-grid price-fields"><Field label="Valor por horário"><input type="number" min="0" step="0.01" value={form.basePrice||0} onChange={e=>set('basePrice',Number(e.target.value))}/></Field><Field label="Duração do horário (min)"><input type="number" min="1" value={form.slotDurationMinutes||60} onChange={e=>set('slotDurationMinutes',Number(e.target.value))}/></Field></div>}
  {form.pricingType==='HOURLY'&&<div className="form-grid price-fields"><Field label="Valor por hora"><input type="number" min="0" step="0.01" value={form.basePrice||0} onChange={e=>set('basePrice',Number(e.target.value))}/></Field><Field label="Passo de duração (min)"><input type="number" min="15" value={form.durationStepMinutes||60} onChange={e=>set('durationStepMinutes',Number(e.target.value))}/></Field><Field label="Mínimo (min)"><input type="number" value={form.minimumDurationMinutes||60} onChange={e=>set('minimumDurationMinutes',Number(e.target.value))}/></Field><Field label="Máximo (min)"><input type="number" value={form.maximumDurationMinutes||240} onChange={e=>set('maximumDurationMinutes',Number(e.target.value))}/></Field></div>}
  {form.pricingType==='DAILY'&&<div className="form-grid price-fields"><Field label="Valor da diária"><input type="number" min="0" step="0.01" value={form.dailyPrice||0} onChange={e=>set('dailyPrice',Number(e.target.value))}/></Field><Field label="Mínimo de dias"><input type="number" min="1" value={form.minimumDays||1} onChange={e=>set('minimumDays',Number(e.target.value))}/></Field><Field label="Máximo de dias"><input type="number" min="1" value={form.maximumDays||7} onChange={e=>set('maximumDays',Number(e.target.value))}/></Field></div>}
  {form.pricingType==='PACKAGE'&&<div className="feature-ready"><PackageOpen/><div><strong>Pacotes serão configurados na tela do espaço</strong><p>Cadastre o espaço primeiro. Depois você poderá adicionar opções como 2h por R$ 150 ou 4h por R$ 270.</p></div></div>}
  </Card>
  <Card><h2>Política inicial</h2><div className="form-grid"><label className="check"><input type="checkbox" checked={Boolean(form.requiresApproval)} onChange={e=>set('requiresApproval',e.target.checked)}/> Reserva precisa de aprovação</label><label className="check"><input type="checkbox" checked={Boolean(form.requiresPayment)} onChange={e=>set('requiresPayment',e.target.checked)}/> Pagamento obrigatório</label></div><p className="muted">Essas regras serão conectadas ao backend na próxima etapa.</p></Card>
  {error&&<div className="alert danger">{error}</div>}<div className="editor-actions"><Link className="btn ghost" to="/app/venues">Cancelar</Link><button className="btn primary">{editing?'Salvar alterações':'Criar espaço'}</button></div></form></>}
